image:
  file: .gitpod.Dockerfile

tasks:
  - name: Boot
    command: open README.md && make start

# Exposed services:
ports:
  - name: Hasura GraphQL APIs
    description: Runs the Hasura Engine APIs
    port: 8080
    visibility: public # Auth issues if private
    onOpen: open-preview
  - name: Adminer
    description: Runs Adminer database Web Client
    port: 8081
    visibility: public
    onOpen: ignore
  - name: Hasura Console
    description: Runs the Hasura Web Console
    port: 9695
    visibility: public
    onOpen: ignore
  - name: Hasura CLI APIs
    description: Runs the Hasura CLI APIs
    port: 9693
    visibility: public # Problems reaching the Hasura API if private
    onOpen: ignore
  - name: React App
    description: Runs the React App
    port: 5173
    visibility: public
    onOpen: ignore
  - name: Postgres
    port: 5432
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ckolkman.vscode-postgres
    - esbenp.prettier-vscode
    - darkriszty.markdown-table-prettify
    - jebbs.plantuml
    - esbenp.prettier-vscode
#   - Codeium.codeium
#   - eamodio.gitlens
